require: rubocop-performance
inherit_from:
  - https://gitlab.com/bsm/misc/raw/master/rubocop/default.yml

AllCops:
  TargetRubyVersion: "2.5"

Naming/FileName:
  Exclude:
    - lib/attribute-defaults.rb

Metrics/BlockLength:
  Enabled: false
